name: hami
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.7.1
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.6
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.14
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmpdec=4.0.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.16
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.51
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
    - accelerate==1.6.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.16
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - anyio==4.9.0
    - attrs==25.3.0
    - baukit==0.0.1
    - bitsandbytes==0.45.5
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - contourpy==1.3.2
    - cycler==0.12.1
    - datasets==3.5.0
    - dill==0.3.8
    - distro==1.9.0
    - dotenv==0.9.9
    - easydict==1.13
    - evaluate==0.4.3
    - filelock==3.13.1
    - fonttools==4.57.0
    - frozenlist==1.6.0
    - fsspec==2024.6.1
    - h11==0.14.0
    - httpcore==1.0.8
    - httpx==0.28.1
    - huggingface-hub==0.30.2
    - idna==3.10
    - jinja2==3.1.4
    - jiter==0.9.0
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2025.4.1
    - kiwisolver==1.4.8
    - markupsafe==3.0.2
    - matplotlib==3.10.1
    - mistral-common==1.5.4
    - mpmath==1.3.0
    - multidict==6.4.3
    - multiprocess==0.70.16
    - networkx==3.3
    - numpy==2.1.2
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.5.1.17
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvtx-cu12==12.6.77
    - openai==1.75.0
    - pandas==2.2.3
    - pillow==11.0.0
    - propcache==0.3.1
    - pyarrow==19.0.1
    - pydantic==2.11.3
    - pydantic-core==2.33.1
    - pyparsing==3.2.3
    - python-dotenv==1.1.0
    - pytz==2025.2
    - pyyaml==6.0.2
    - referencing==0.36.2
    - regex==2024.11.6
    - requests==2.32.3
    - rpds-py==0.24.0
    - safetensors==0.5.3
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - sniffio==1.3.1
    - sympy==1.13.1
    - tenacity==9.1.2
    - threadpoolctl==3.6.0
    - tiktoken==0.9.0
    - tokenizers==0.21.1
    - torch==2.6.0+cu126
    - torchaudio==2.6.0+cu126
    - torchvision==0.21.0+cu126
    - tqdm==4.67.1
    - transformers==4.51.3
    - triton==3.2.0
    - typing-extensions==4.12.2
    - typing-inspection==0.4.0
    - tzdata==2025.2
    - urllib3==2.4.0
    - xxhash==3.5.0
    - yarl==1.20.0
